### ISSUE TITLE
Missing Environment variables - from latest build

### ISSUE THREAD

**Issue by datdamnzotz** [mrcory/Unraiad_Docker_Templates#1]
SIGNATURE: '<change me to something unique>' # The Secret used to hash your password in the browser, 20+ characters recommended
EMAIL_FROM_ADDRESS: '' # Email address to send from, will default to 'no-reply@orcpub.com'

**Comment by mrcory** [comment]
Added as of bb61053b413c4895e33b5d7cd210fea91b894035
